baseurl: '/'
permalink: pretty
title: 'Inkan.link'

logo:
  mobile: "images/logo/SquircleLogoInkan.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/SquircleLogoInkan.svg"
  desktop_height: "50px"
  desktop_width: "50px"

collections:
  services:
    output: true
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: "team"
      type: "team"
    values:
      layout: "team"

sass:
  indentWidth: 2
  style: compact # possible values: nested expanded compact compressed
  precision: 8

plugins:
  - jekyll-environment-variables
  - github-pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
